server:
  port: 8001

spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/tb_order?useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: yuri
#    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: localhost:8848
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8050/eureka

