server:
  port: 8040
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tb_order?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: yuri
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: none
      httpclient:
        enabled: true
        max-connections: 200 #最大连接属
        max-connections-per-route: 50 #每个路径的最大连接数

#      discovery:
#        cluster-name: HZ  #集群名称
#        namespace: dev 命名空间 填写id
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8050/eureka


