server:
  port: 8030
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: yuri
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: localhost:8848
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8050/eureka
